### ISSUE TITLE
Does not push on first and crashes on second attempt

### ISSUE THREAD

**Issue by simonbromberg** [Dwarven/PushMeBaby#1]
SocketRead: read(5) error 2
PushMeBaby[90270:13348525] SSLWrite(): -9806 0

And then press push again and it crashes on line 181 [self disconnect] of ApplicationDelegate.m.

Using macOS 10.13.1 (17B48), Xcode 9.1 (9B55)

**Comment by simonbromberg** [comment]
Noticed "Guaranteed keychain has the corresponding private keys in your Mac."
Not quite sure what that means but perhaps related to that.

**Comment by simonbromberg** [comment]
Yup, fixing the local certificates in the keychain got it working. I suggest this step be clarified further and highlighted better in the Readme and would be useful if the error was handled more gracefully in the application.

Instead of "Guaranteed keychain has the corresponding private keys in your Mac." I assume you meant "Verify that the local keychain has the corresponding certificates and private keys on your Mac"  (Was a bit confused by the phrase "Guaranteed keychain" at first.)

**Comment by Dwarven** [comment]
Thx~ I have updated README and the code.
![image](https://user-images.githubusercontent.com/5902224/32881767-3b880ab8-caed-11e7-9d3e-343f0d3b9b55.png)
